<?php

namespace ContainerKAqHUj3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioAlice_DataLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'nelmio_alice.data_loader' shared service.
     *
     * @return \Nelmio\Alice\Loader\SimpleDataLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'alice'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DataLoaderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'alice'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'IsAServiceTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'alice'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'SimpleDataLoader.php';

        return $container->services['nelmio_alice.data_loader'] = new \Nelmio\Alice\Loader\SimpleDataLoader(($container->privates['nelmio_alice.fixture_builder.simple'] ?? $container->load('getNelmioAlice_FixtureBuilder_SimpleService')), ($container->privates['nelmio_alice.generator.double_pass'] ?? $container->load('getNelmioAlice_Generator_DoublePassService')));
    }
}
