<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKhPepi\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKhPepi/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerNKhPepi.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerNKhPepi\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerNKhPepi\App_KernelTestDebugContainer([
    'container.build_hash' => 'NKhPepi',
    'container.build_id' => '87b1ad2a',
    'container.build_time' => 1654260946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKhPepi');
